apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  template:
    spec:
      tolerations:
        - key: "node_group"
          value: "infra-production-on-demand"
          operator: "Equal"
          effect: "NoSchedule"
      containers:
        - name: operator
          args:
            - --zap-log-level=error
