apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  template:
    spec:
      tolerations:
        - key: "node_group"
          value: "infra-production-on-demand"
          operator: "Equal"
          effect: "NoSchedule"
      nodeSelector:
        node_group: "infra-production-on-demand"
      containers:
        - command:
            - /manager
          args:
            - --zap-log-level=error
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: rabbitmqoperator/cluster-operator:2.1.0
          name: operator
          ports:
            - containerPort: 9782
              name: metrics
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi

